name: Backend Lint and Test before merge main

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.18.1

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run Lint
        run: |
          cd backend
          npm run lint
  test:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.18.1

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run Test
        run: |
          cd backend
          npm run test
